config/routes.rb
Rails.application.routes.draw do
  root 'boards#index'

  resources :boards do 
    resources :lists
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board.rb
class Board < ApplicationRecord
  has_many :lists, dependent: :destroy
end

app/models/list.rb
class List < ApplicationRecord
  belongs_to :board
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :set_board, only: [:show, :edit, :update, :destroy]
  
  def index
    @boards = Board.all
  end

  def show
  end

  def new
    @board = Board.new
  end

  def create
    @board = Board.new(board_params)
    if @board.save
    redirect_to boards_path
    else
      render :new
    end
  end


  def edit
  end


  def update
    if @board.update(board_params)
      redirect_to boards_path
    else
      render :edit
    end
  end

  def destroy
    @board.destroy
    redirect_to boards_path
  end

  private

    def set_board
      @board = Board.find(params[:id])
    end

    def board_params
      params.require(:board).permit(:boardtitle)
    end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_board
  before_action :set_list, only: [:show, :edit, :update, :destroy]
  def index
    @lists = @board.lists
  end

  def show
  end

  def new
    @list = @board.lists.new
  end

  def create
    @list = @board.lists.new(list_params)
    if @list.save
      redirect_to [@board, @list]
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @list.update(list_params)
      redirect_to [@board, @list]
    else
      render :edit
    end
  end

  def destroy
    @list.destroy
    redirect_to board_lists_path(@board)
  end
  
  private

    def set_board
      @board = Board.find(params[:board_id])
    end

    def set_list
      @list = List.find(params[:id])
    end

    def list_params
      params.require(:list).permit(:listname)
    end
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/boards/edit.html.erb
<h1>Boards#edit</h1>
<p>Find me in app/views/boards/edit.html.erb</p>

app/views/boards/index.html.erb
<h1>Boards</h1>
<% @boards.each do |board| %>
  <div>
  <p><%= link_to board.boardtitle, board_path(board) %>
  </div>
<% end %>
<%= link_to "Add a new board", new_board_path, class: "waves-effect waves-light btn-small" %>

app/views/boards/new.html.erb
<h3>Add a new Board</h3>
<%= form_with(model: @board, local: true,  class: "form") do |f|%>
  <%= f.label :Title%>
  <%= f.text_field :boardtitle, class: "input" %>
  <%= f.submit nil, class: "waves-effect waves-light btn-small" %>
<%end%>

app/views/boards/show.html.erb
<h1><%= @board.boardtitle %></h1>

<%= link_to "Edit", edit_board_path(@board), class: "bwaves-effect waves-light btn-small" %>
<%= link_to "Delete", @board, method: :delete, class: "bwaves-effect waves-light btn-small" %>
<br />
<br />
<br />
<h4>Lists:</h4>
<ul>
  <% @board.lists.each do |list| %>
    <li>
      <%= link_to list.listname, [@board, list] %>
    </li>
  <% end %>
</ul>
<br />
<br />
<br />
<%= link_to "Add new list", new_board_list_path(@board), class: "bwaves-effect waves-light btn-small" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTrollo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<h1>Lists</h1>
<% @lists.each do |list| %>
  <div>
  <p><%= link_to list.listname, list_path(@list) %>
  </div>
<% end %>"
<%= link_to "Add a new list", new_board_list_path, class: "waves-effect waves-light btn-small" %>

app/views/lists/new.html.erb
<h1>Add new list</h1>
<%= form_for [@board, @list] do |f| %>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :listname, required: true, autofocus: true %>
  </div>
  <p>
  <label>
    <input type="checkbox" />
    <span>Priority</span>
    <%= f.check_box :priority, {}, 'true', 'false' %>
  </label>
</p>
<p>
<br />

  <%= f.submit nil, class: "waves-effect waves-light btn-small" %>
<% end %>

app/views/lists/show.html.erb
<h1><%= @list.listname %></h1>